/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as CommonRouteImport } from './routes/_common'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingIndexRouteImport } from './routes/_onboarding/index'
import { Route as OnboardingConnectRouteImport } from './routes/_onboarding/connect'
import { Route as CommonTermsRouteImport } from './routes/_common/terms'
import { Route as CommonSupportRouteImport } from './routes/_common/support'
import { Route as CommonPolicyRouteImport } from './routes/_common/policy'
import { Route as AppRulesIndexRouteImport } from './routes/_app/rules/index'
import { Route as AppPoolIndexRouteImport } from './routes/_app/pool/index'
import { Route as AppNotificationIndexRouteImport } from './routes/_app/notification/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppPoolPoolIdIndexRouteImport } from './routes/_app/pool/$poolId/index'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonRoute = CommonRouteImport.update({
  id: '/_common',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingConnectRoute = OnboardingConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => OnboardingRoute,
} as any)
const CommonTermsRoute = CommonTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => CommonRoute,
} as any)
const CommonSupportRoute = CommonSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CommonRoute,
} as any)
const CommonPolicyRoute = CommonPolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => CommonRoute,
} as any)
const AppRulesIndexRoute = AppRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => AppRoute,
} as any)
const AppPoolIndexRoute = AppPoolIndexRouteImport.update({
  id: '/pool/',
  path: '/pool/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationIndexRoute = AppNotificationIndexRouteImport.update({
  id: '/notification/',
  path: '/notification/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppPoolPoolIdIndexRoute = AppPoolPoolIdIndexRouteImport.update({
  id: '/pool/$poolId/',
  path: '/pool/$poolId/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/policy': typeof CommonPolicyRoute
  '/support': typeof CommonSupportRoute
  '/terms': typeof CommonTermsRoute
  '/connect': typeof OnboardingConnectRoute
  '/': typeof OnboardingIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/notification': typeof AppNotificationIndexRoute
  '/pool': typeof AppPoolIndexRoute
  '/rules': typeof AppRulesIndexRoute
  '/pool/$poolId': typeof AppPoolPoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/policy': typeof CommonPolicyRoute
  '/support': typeof CommonSupportRoute
  '/terms': typeof CommonTermsRoute
  '/connect': typeof OnboardingConnectRoute
  '/': typeof OnboardingIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/notification': typeof AppNotificationIndexRoute
  '/pool': typeof AppPoolIndexRoute
  '/rules': typeof AppRulesIndexRoute
  '/pool/$poolId': typeof AppPoolPoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_common': typeof CommonRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_common/policy': typeof CommonPolicyRoute
  '/_common/support': typeof CommonSupportRoute
  '/_common/terms': typeof CommonTermsRoute
  '/_onboarding/connect': typeof OnboardingConnectRoute
  '/_onboarding/': typeof OnboardingIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/notification/': typeof AppNotificationIndexRoute
  '/_app/pool/': typeof AppPoolIndexRoute
  '/_app/rules/': typeof AppRulesIndexRoute
  '/_app/pool/$poolId/': typeof AppPoolPoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/policy'
    | '/support'
    | '/terms'
    | '/connect'
    | '/'
    | '/dashboard'
    | '/notification'
    | '/pool'
    | '/rules'
    | '/pool/$poolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/policy'
    | '/support'
    | '/terms'
    | '/connect'
    | '/'
    | '/dashboard'
    | '/notification'
    | '/pool'
    | '/rules'
    | '/pool/$poolId'
  id:
    | '__root__'
    | '/_app'
    | '/_common'
    | '/_onboarding'
    | '/_common/policy'
    | '/_common/support'
    | '/_common/terms'
    | '/_onboarding/connect'
    | '/_onboarding/'
    | '/_app/dashboard/'
    | '/_app/notification/'
    | '/_app/pool/'
    | '/_app/rules/'
    | '/_app/pool/$poolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CommonRoute: typeof CommonRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_common': {
      id: '/_common'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof CommonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/': {
      id: '/_onboarding/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/connect': {
      id: '/_onboarding/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof OnboardingConnectRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_common/terms': {
      id: '/_common/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof CommonTermsRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/support': {
      id: '/_common/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof CommonSupportRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/policy': {
      id: '/_common/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof CommonPolicyRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_app/rules/': {
      id: '/_app/rules/'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof AppRulesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pool/': {
      id: '/_app/pool/'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof AppPoolIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notification/': {
      id: '/_app/notification/'
      path: '/notification'
      fullPath: '/notification'
      preLoaderRoute: typeof AppNotificationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pool/$poolId/': {
      id: '/_app/pool/$poolId/'
      path: '/pool/$poolId'
      fullPath: '/pool/$poolId'
      preLoaderRoute: typeof AppPoolPoolIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppNotificationIndexRoute: typeof AppNotificationIndexRoute
  AppPoolIndexRoute: typeof AppPoolIndexRoute
  AppRulesIndexRoute: typeof AppRulesIndexRoute
  AppPoolPoolIdIndexRoute: typeof AppPoolPoolIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppNotificationIndexRoute: AppNotificationIndexRoute,
  AppPoolIndexRoute: AppPoolIndexRoute,
  AppRulesIndexRoute: AppRulesIndexRoute,
  AppPoolPoolIdIndexRoute: AppPoolPoolIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CommonRouteChildren {
  CommonPolicyRoute: typeof CommonPolicyRoute
  CommonSupportRoute: typeof CommonSupportRoute
  CommonTermsRoute: typeof CommonTermsRoute
}

const CommonRouteChildren: CommonRouteChildren = {
  CommonPolicyRoute: CommonPolicyRoute,
  CommonSupportRoute: CommonSupportRoute,
  CommonTermsRoute: CommonTermsRoute,
}

const CommonRouteWithChildren =
  CommonRoute._addFileChildren(CommonRouteChildren)

interface OnboardingRouteChildren {
  OnboardingConnectRoute: typeof OnboardingConnectRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingConnectRoute: OnboardingConnectRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CommonRoute: CommonRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
